import { UserRole } from '../types/user';

export const PERMISSIONS = {
  // Students
  STUDENTS_VIEW: 'students.view',
  STUDENTS_CREATE: 'students.create',
  STUDENTS_UPDATE: 'students.update',
  STUDENTS_DELETE: 'students.delete',

  // Faculty
  FACULTY_VIEW: 'faculty.view',
  FACULTY_CREATE: 'faculty.create',
  FACULTY_UPDATE: 'faculty.update',

  // Attendance
  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_CREATE: 'attendance.create',
  ATTENDANCE_UPDATE: 'attendance.update',

  // Results & Exams
  RESULTS_VIEW: 'results.view',
  RESULTS_CREATE: 'results.create',
  RESULTS_PUBLISH: 'results.publish',

  // Fees & Finance
  FEES_VIEW: 'fees.view',
  FEES_CREATE: 'fees.create',
  FEES_UPDATE: 'fees.update',
  FEES_REFUND: 'fees.refund',

  // Library
  LIBRARY_VIEW: 'library.view',
  LIBRARY_MANAGE: 'library.manage',

  // Hostel & Transport
  HOSTEL_VIEW: 'hostel.view',
  HOSTEL_MANAGE: 'hostel.manage',
  TRANSPORT_VIEW: 'transport.view',
  TRANSPORT_MANAGE: 'transport.manage',

  // Placements
  PLACEMENTS_VIEW: 'placements.view',
  PLACEMENTS_MANAGE: 'placements.manage',

  // Reports
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',

  // System Administration
  SYSTEM_CONFIG: 'system.config',
  AUDIT_LOGS: 'system.audit',
} as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  SYSTEM_ADMIN: Object.values(PERMISSIONS),
  MANAGEMENT: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.AUDIT_LOGS,
  ],
  PRINCIPAL: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_PUBLISH,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  DEAN: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  HOD: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  FACULTY: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CREATE,
    PERMISSIONS.ATTENDANCE_UPDATE,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_CREATE,
  ],
  STUDENT: [
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.LIBRARY_VIEW,
    PERMISSIONS.PLACEMENTS_VIEW,
  ],
  PARENT: [
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.FEES_VIEW,
  ],
  ADMISSION_TEAM: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_UPDATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  EXAM_CELL: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.RESULTS_CREATE,
    PERMISSIONS.RESULTS_PUBLISH,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  FINANCE: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_CREATE,
    PERMISSIONS.FEES_UPDATE,
    PERMISSIONS.FEES_REFUND,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  HR: [
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.FACULTY_CREATE,
    PERMISSIONS.FACULTY_UPDATE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  LIBRARIAN: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.LIBRARY_VIEW,
    PERMISSIONS.LIBRARY_MANAGE,
  ],
  CAMPUS_OPERATIONS: [
    PERMISSIONS.HOSTEL_VIEW,
    PERMISSIONS.HOSTEL_MANAGE,
    PERMISSIONS.TRANSPORT_VIEW,
    PERMISSIONS.TRANSPORT_MANAGE,
  ],
  PLACEMENT_TEAM: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.PLACEMENTS_VIEW,
    PERMISSIONS.PLACEMENTS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  LMS_ADMIN: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  RESEARCH_TEAM: [
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  INVENTORY_MANAGER: [
    PERMISSIONS.REPORTS_VIEW,
  ],
  COMPLIANCE_OFFICER: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.AUDIT_LOGS,
  ],
  HELPDESK_AGENT: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
  ],
  GRIEVANCE_OFFICER: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
  ],
  SECURITY_ADMIN: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.AUDIT_LOGS,
  ],
  TENANT_ADMIN: Object.values(PERMISSIONS),
  BI_ANALYST: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.FACULTY_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.RESULTS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],
};
