"""create_groups_6_to_11_tables

Revision ID: 423b328bad87
Revises: f1a7868766e6
Create Date: 2026-09-10 10:29:17.123965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423b328bad87'
down_revision: Union[str, Sequence[str], None] = 'f1a7868766e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('university_id', sa.Uuid(), nullable=False),
    sa.Column('isbn', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('total_copies', sa.Integer(), nullable=False),
    sa.Column('available_copies', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_books_isbn'), 'library_books', ['isbn'], unique=False)
    op.create_index(op.f('ix_library_books_university_id'), 'library_books', ['university_id'], unique=False)
    op.create_table('placement_drives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('university_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('package_details', sa.String(length=255), nullable=True),
    sa.Column('drive_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_drives_university_id'), 'placement_drives', ['university_id'], unique=False)
    op.create_table('ai_conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('hostels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('warden_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_campus_id'), 'hostels', ['campus_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('transport_routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campus_id', sa.Uuid(), nullable=False),
    sa.Column('route_number', sa.String(length=50), nullable=False),
    sa.Column('route_name', sa.String(length=255), nullable=False),
    sa.Column('start_location', sa.String(length=255), nullable=False),
    sa.Column('end_location', sa.String(length=255), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_routes_campus_id'), 'transport_routes', ['campus_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_table('hostel_rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostel_id', sa.Uuid(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupied_count', sa.Integer(), nullable=False),
    sa.Column('monthly_fee', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_rooms_hostel_id'), 'hostel_rooms', ['hostel_id'], unique=False)
    op.create_table('transport_vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_vehicles_route_id'), 'transport_vehicles', ['route_id'], unique=False)
    op.create_table('fee_structures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('university_id', sa.Uuid(), nullable=False),
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_structures_academic_year_id'), 'fee_structures', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_program_id'), 'fee_structures', ['program_id'], unique=False)
    op.create_index(op.f('ix_fee_structures_university_id'), 'fee_structures', ['university_id'], unique=False)
    op.create_table('book_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['library_books.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_issues_book_id'), 'book_issues', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_issues_student_id'), 'book_issues', ['student_id'], unique=False)
    op.create_table('hostel_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vacate_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['hostel_rooms.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_allocations_room_id'), 'hostel_allocations', ['room_id'], unique=False)
    op.create_index(op.f('ix_hostel_allocations_student_id'), 'hostel_allocations', ['student_id'], unique=False)
    op.create_table('placement_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('placement_drive_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('application_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['placement_drive_id'], ['placement_drives.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_applications_placement_drive_id'), 'placement_applications', ['placement_drive_id'], unique=False)
    op.create_index(op.f('ix_placement_applications_student_id'), 'placement_applications', ['student_id'], unique=False)
    op.create_table('student_fees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('fee_structure_id', sa.Uuid(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_fees_fee_structure_id'), 'student_fees', ['fee_structure_id'], unique=False)
    op.create_index(op.f('ix_student_fees_student_id'), 'student_fees', ['student_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('semester_id', sa.Uuid(), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('total_credits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_academic_year_id'), 'transcripts', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_transcripts_semester_id'), 'transcripts', ['semester_id'], unique=False)
    op.create_index(op.f('ix_transcripts_student_id'), 'transcripts', ['student_id'], unique=False)
    op.create_table('transport_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('route_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('stop_location', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transport_allocations_route_id'), 'transport_allocations', ['route_id'], unique=False)
    op.create_index(op.f('ix_transport_allocations_student_id'), 'transport_allocations', ['student_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_course_offering_id'), 'assignments', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_assignments_faculty_id'), 'assignments', ['faculty_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.Column('passing_marks', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_course_offering_id'), 'exams', ['course_offering_id'], unique=False)
    op.create_table('learning_materials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_materials_course_offering_id'), 'learning_materials', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_learning_materials_faculty_id'), 'learning_materials', ['faculty_id'], unique=False)
    op.create_table('library_fines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_issue_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_issue_id'], ['book_issues.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_fines_book_issue_id'), 'library_fines', ['book_issue_id'], unique=False)
    op.create_index(op.f('ix_library_fines_student_id'), 'library_fines', ['student_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_fee_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_fee_id'], ['student_fees.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_student_fee_id'), 'payments', ['student_fee_id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    op.create_table('assignment_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_submissions_assignment_id'), 'assignment_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_student_id'), 'assignment_submissions', ['student_id'], unique=False)
    op.create_table('exam_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_results_exam_id'), 'exam_results', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_results_student_id'), 'exam_results', ['student_id'], unique=False)
    op.create_table('exam_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('classroom_id', sa.Uuid(), nullable=True),
    sa.Column('invigilator_faculty_id', sa.Uuid(), nullable=True),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['invigilator_faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_schedules_classroom_id'), 'exam_schedules', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_exam_id'), 'exam_schedules', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_schedules_invigilator_faculty_id'), 'exam_schedules', ['invigilator_faculty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_schedules_invigilator_faculty_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_exam_id'), table_name='exam_schedules')
    op.drop_index(op.f('ix_exam_schedules_classroom_id'), table_name='exam_schedules')
    op.drop_table('exam_schedules')
    op.drop_index(op.f('ix_exam_results_student_id'), table_name='exam_results')
    op.drop_index(op.f('ix_exam_results_exam_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index(op.f('ix_assignment_submissions_student_id'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_assignment_id'), table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_student_fee_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_library_fines_student_id'), table_name='library_fines')
    op.drop_index(op.f('ix_library_fines_book_issue_id'), table_name='library_fines')
    op.drop_table('library_fines')
    op.drop_index(op.f('ix_learning_materials_faculty_id'), table_name='learning_materials')
    op.drop_index(op.f('ix_learning_materials_course_offering_id'), table_name='learning_materials')
    op.drop_table('learning_materials')
    op.drop_index(op.f('ix_exams_course_offering_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_assignments_faculty_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_course_offering_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_transport_allocations_student_id'), table_name='transport_allocations')
    op.drop_index(op.f('ix_transport_allocations_route_id'), table_name='transport_allocations')
    op.drop_table('transport_allocations')
    op.drop_index(op.f('ix_transcripts_student_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_semester_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_academic_year_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_student_fees_student_id'), table_name='student_fees')
    op.drop_index(op.f('ix_student_fees_fee_structure_id'), table_name='student_fees')
    op.drop_table('student_fees')
    op.drop_index(op.f('ix_placement_applications_student_id'), table_name='placement_applications')
    op.drop_index(op.f('ix_placement_applications_placement_drive_id'), table_name='placement_applications')
    op.drop_table('placement_applications')
    op.drop_index(op.f('ix_hostel_allocations_student_id'), table_name='hostel_allocations')
    op.drop_index(op.f('ix_hostel_allocations_room_id'), table_name='hostel_allocations')
    op.drop_table('hostel_allocations')
    op.drop_index(op.f('ix_book_issues_student_id'), table_name='book_issues')
    op.drop_index(op.f('ix_book_issues_book_id'), table_name='book_issues')
    op.drop_table('book_issues')
    op.drop_index(op.f('ix_fee_structures_university_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_program_id'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structures_academic_year_id'), table_name='fee_structures')
    op.drop_table('fee_structures')
    op.drop_index(op.f('ix_transport_vehicles_route_id'), table_name='transport_vehicles')
    op.drop_table('transport_vehicles')
    op.drop_index(op.f('ix_hostel_rooms_hostel_id'), table_name='hostel_rooms')
    op.drop_table('hostel_rooms')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_transport_routes_campus_id'), table_name='transport_routes')
    op.drop_table('transport_routes')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_hostels_campus_id'), table_name='hostels')
    op.drop_table('hostels')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_placement_drives_university_id'), table_name='placement_drives')
    op.drop_table('placement_drives')
    op.drop_index(op.f('ix_library_books_university_id'), table_name='library_books')
    op.drop_index(op.f('ix_library_books_isbn'), table_name='library_books')
    op.drop_table('library_books')
    # ### end Alembic commands ###
