import { User, ScheduleItem, Course, Announcement } from '../types/auth';

export const mockStudentUser: User = {
  id: 'usr_student_01',
  name: 'Alex Johnson',
  email: 'alex.johnson@university.edu',
  phone: '+1 (555) 234-5678',
  role: 'student',
  department: 'Artificial Intelligence & Computer Science',
  studentId: 'US-2026-AI-042',
  enrolledYear: '2024 - 2028 (Year 3)',
  gpa: 3.86,
  attendanceRate: 94.8,
  creditsEarned: 88,
  totalCredits: 120,
};

export const mockFacultyUser: User = {
  id: 'usr_faculty_02',
  name: 'Dr. Sarah Mitchell',
  email: 'sarah.mitchell@university.edu',
  phone: '+1 (555) 987-6543',
  role: 'faculty',
  department: 'Department of Computer Science',
  studentId: 'FAC-CS-108',
  enrolledYear: 'Tenured Faculty',
  gpa: 4.0,
  attendanceRate: 99.2,
  creditsEarned: 120,
  totalCredits: 120,
};

export const mockSchedule: ScheduleItem[] = [
  {
    id: 'sch_1',
    code: 'CS-401',
    title: 'Deep Learning & Neural Architectures',
    time: '09:00 AM - 10:30 AM',
    day: 'Monday',
    room: 'Hall C-302',
    instructor: 'Prof. A. Vance',
    color: '#2563eb',
    status: 'Ongoing',
  },
  {
    id: 'sch_2',
    code: 'DS-310',
    title: 'Big Data Distributed Systems',
    time: '11:00 AM - 12:30 PM',
    day: 'Monday',
    room: 'Lab 4B',
    instructor: 'Dr. S. Mitchell',
    color: '#0ea5e9',
    status: 'Upcoming',
  },
  {
    id: 'sch_3',
    code: 'MATH-250',
    title: 'Stochastic Calculus & Optimization',
    time: '02:00 PM - 03:30 PM',
    day: 'Monday',
    room: 'Auditorium 1',
    instructor: 'Dr. K. Rao',
    color: '#6366f1',
    status: 'Upcoming',
  },
  {
    id: 'sch_4',
    code: 'AI-480',
    title: 'Autonomous Robotics & Vision',
    time: '10:00 AM - 11:30 AM',
    day: 'Tuesday',
    room: 'Robotics Wing R1',
    instructor: 'Dr. E. Thorne',
    color: '#10b981',
    status: 'Upcoming',
  },
];

export const mockCourses: Course[] = [
  {
    id: 'c1',
    code: 'CS-401',
    title: 'Deep Learning & Neural Architectures',
    credits: 4,
    instructor: 'Prof. A. Vance',
    progress: 72,
    schedule: 'Mon / Wed 09:00 AM',
    grade: 'A',
  },
  {
    id: 'c2',
    code: 'DS-310',
    title: 'Big Data Distributed Systems',
    credits: 3,
    instructor: 'Dr. S. Mitchell',
    progress: 65,
    schedule: 'Mon / Thu 11:00 AM',
    grade: 'A-',
  },
  {
    id: 'c3',
    code: 'MATH-250',
    title: 'Stochastic Calculus & Optimization',
    credits: 4,
    instructor: 'Dr. K. Rao',
    progress: 80,
    schedule: 'Mon / Fri 02:00 PM',
    grade: 'A',
  },
  {
    id: 'c4',
    code: 'AI-480',
    title: 'Autonomous Robotics & Vision',
    credits: 3,
    instructor: 'Dr. E. Thorne',
    progress: 58,
    schedule: 'Tue / Thu 10:00 AM',
    grade: 'B+',
  },
  {
    id: 'c5',
    code: 'ETH-102',
    title: 'AI Safety & Technological Ethics',
    credits: 2,
    instructor: 'Prof. L. Chen',
    progress: 90,
    schedule: 'Wed 03:00 PM',
    grade: 'A+',
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann_1',
    title: 'Fall 2026 Mid-Semester Exam Schedule Published',
    date: 'Sep 10, 2026',
    category: 'Exam',
    content: 'The finalized timetable for the midterm examinations is now live on the student portal.',
  },
  {
    id: 'ann_2',
    title: 'AI Research Symposium & Hackathon Registrations Open',
    date: 'Sep 15, 2026',
    category: 'Academic',
    content: 'Submit your research abstracts or register team projects by end of week for the annual campus symposium.',
  },
  {
    id: 'ann_3',
    title: 'Digital Library 24/7 Extended Access',
    date: 'Sep 08, 2026',
    category: 'Campus',
    content: 'All online journal repositories and study wings are now operating with round-the-clock student badge access.',
  },
];
